beParents/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('accounts.urls', namespace='index')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('map/', include('map.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('search/', include('search.urls')),
    path('centers/', include('centers.urls')),
    path('mypage/', include('mypage.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

centers/urls.py
from django.urls import path
from . import views

app_name = 'centers'

urlpatterns = [

    path('<int:center_id>/', views.index, name = 'index'),
    path('<int:center_id>/reviews/new', views.reviews, name = 'reviews'),
    path('<int:center_id>/reviews/save', views.save, name = 'save'),
    path('<int:center_id>/<int:review_id>/edit', views.edit, name = 'edit'),
    path('<int:center_id>/<int:review_id>/update', views.update, name = 'update'),
    path('<int:center_id>/<int:review_id>/delete/', views.delete, name = 'delete'),
    path('<int:center_id>/like/', views.like, name = 'like'),

]

map/urls.py
from django.urls import path

from . import views

app_name = 'map'

urlpatterns = [
    path('', views.index, name = 'index'),
    #path('<int:center_id>/center_summary/', views.center_summary, name = 'center_summary'),
    path('ajax/', views.ajax, name = 'ajax'),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [

    path('', views.index, name = 'index'),
    path('center_list/', views.center_list, name = 'center_list'),
    path('center_list_ajax/', views.center_list_ajax, name = 'center_list_ajax'),

]

search/models.py
from django.db import models
from django.contrib.auth.models import User
from centers.models import Center, CenterReview

# Create your models here.

class Search(models.Model):
    search_query = models.TextField()
    searched_at = models.DateTimeField()
    # search_users = models.ManyToManyField(User, through = 'SearchCount', related_name='search_centers', null = True)

    def __str__(self):
        return f'{self.search_query}'

#class SearchCount(models.Model) :
    #center = models.ForeignKey(Center, on_delete=models.CASCADE)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    #created_at = models.DateTimeField(auto_now_add=True, null = True)

search/views.py
from django.shortcuts import render, redirect
from .models import Search
from django.contrib import messages
from django.utils import timezone
from django.views.generic import ListView
from .models import Center, CenterReview
from django.db.models import Q
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Avg, Count
from haversine import haversine
from collections import Counter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def index(request):

    hashtags = Center.objects.values('hashtags')

    hashtag_list = [] # 전체 hashtag 리스트를 만든다

    for hashtag in hashtags :
        values = hashtag['hashtags']
        for value in values :
            hashtag_list.append(value)
    
    hashtag_count = Counter(hashtag_list) # hashtag couter 딕셔너리를 만든다. ex) {'아동발달' : 5, '미술치료' : 2} / 갯수많은 순서대로 자동 sorting
    top10_dict = dict(Counter(hashtag_count).most_common(10))
    hashtag_top10 = list(top10_dict.keys())
    
    
    context = {
        'hashtag_top10' : hashtag_top10
        }
    
    return render(request, 'search/index.html', context)


def center_list(request):
    
    try:
        userX = request.GET['userX']
        userY = request.GET['userY']
        user_location = (float(userX), float(userY))
    except:
        user_location = (37.5666103, 126.9783882)

    centers = None
    query = None
    if 'query' in request.GET:
        query = request.GET.get('query')
        all_centers = Center.objects.all().filter(Q (center_name__icontains=query) | Q (center_type__icontains=query) | Q (hashtags__icontains=query))
  
        center_list = []

        for center in all_centers:
            center_location = (center.x, center.y) 
            user_distance = haversine(user_location, center_location, unit= 'km')
            reviews = CenterReview.objects.values('center').annotate(Avg('score'), Count('score')).filter(center=center)


            center = {
                'id': center.id ,
                'name' : center.center_name,
                'address' : center.center_address,
                'x' : center.x,
                'y' : center.y,
                'distance' : round(user_distance, 3),
                'type' : center.center_type,
                'review' : reviews
            }
            center_list.append(center)

        center_list.sort(key=(lambda x: x['distance'])) # 사용자 거리순 정렬

        paginator = Paginator(center_list, 10)
        page = request.GET.get('page')


        try:
            centers = paginator.page(page)
        except PageNotAnInteger:
            centers = paginator.page(1)
        except EmptyPage:
            centers = paginator.page(paginator.num_pages)




    
    context = { 
                'centers' : centers,
                'query' : query,
                'userX' : userX,
                'userY' : userY,
    
            }
    

    return render(request, 'search/center_list.html', context)



def center_list_ajax(request):
    try:
        userX = request.GET['userX']
        userY = request.GET['userY']
        user_location = (float(userX), float(userY))
    except:
        user_location = (37.5666103, 126.9783882)


    centers = None
    query = None
    if 'query' in request.GET:
        query = request.GET.get('query')
        all_centers = Center.objects.all().filter(
            Q (center_name__icontains=query) | Q (center_type__icontains=query) | Q (hashtags__icontains=query)
        )



        center_list = []

        for center in all_centers:
            center_location = (center.x, center.y) 
            user_distance = haversine(user_location, center_location, unit= 'km')
            reviews = CenterReview.objects.values('center').annotate(Avg('score'), Count('score')).filter(center=center)


            center = {
                'id': center.id ,
                'name' : center.center_name,
                'address' : center.center_address,
                'x' : center.x,
                'y' : center.y,
                'distance' : round(user_distance, 3),
                'type' : center.center_type,
                'review' : reviews
            }
            center_list.append(center)

        center_list.sort(key=(lambda x: x['distance'])) # 사용자 거리순 정렬


        paginator = Paginator(center_list, 10)
        page = request.GET.get('page')

        


        try:
            centers = paginator.page(page)
        except PageNotAnInteger:
            centers = paginator.page(1)
        except EmptyPage:
            centers = None
            



    
    context = { 
                'centers' : centers,
                'query' : query,

            }
    

    return render(request, 'search/center_list_ajax.html', context)

search/templates/search/center_list.html
{% extends "navbar.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'search/result_style.css' %}" type="text/css" />
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="module" src="{% static 'search/result.js' %}" defer></script>

{% endblock %}

{% block content %}

<!-- search word -->
<section id="search-word" class="header">
    <button type="button" class="btn back__btn">
        <i class="fas fa-chevron-left"></i>
    </button>

    <p class="search-bar__input">{{ query }}</p>

    <a href="{% url 'search:index' %}" class="search-bar__icon cancel__icon">
        <i class="fas fa-times-circle"></i>
    </a>
</section>

<!-- result list  -->
<div class="search__result list__container">
    <div class="list__sort-by">
        <div class="sort-by__current">
            <span class="sort-by__method">거리순</span>
            <span class="sort-by__btn">
                <i class="fas fa-angle-down"></i>
            </span>
        </div>
        <ul class="sort-by__option inactive">
            <li class="option__item" id="by-distance">
                <span class="option__description">거리순</span>
                <span class="option__check-mark">
                    <i class="fas fa-check"></i>
                </span>
            </li>
            <li class="option__item" id="by-score">
                <span class="option__description">평점순</span>
                <span class="option__check-mark inactive">
                    <i class="fas fa-check"></i>
                </span>
            </li>
        </ul>
    </div>



    {% if centers %}
    <ul class="center__list main">
        <ul id="center__parts">
        {% for center in centers %}
        <li class="center__item" data-distance = "{{ center.distance }}" data-score = "{{ center.review.0.score__avg|floatformat }}">
            <div class="center__summary__main">
                <a href="{% url 'centers:index' center.id %}" class="center__name" target="_blank">{{ center.name }}</a>
                <div class="center__location">
                    <span class="center__distance">{{ center.distance }}</span>
                    <span class="divider"></span>
                    <span class="center__address">{{ center.address }}</span>
                </div>
                
                <div class="center__review">

                    {% if center.review %}
                    <span class="center__average">★ {{ center.review.0.score__avg|floatformat }}</span>  

                    {% else %}
                    <span class="center__average">★ 0.0</span> 
                    {% endif %}
                    
                    <span class="divider"></span>
                    <span class="center__counts">리뷰  
                        {% if center.review %}
                        <span>{{ center.review.0.score__count }}</span>  
                        {% else %}
                        <span>0</span>
                        {% endif %}</span>
                        
                </div>
            </div> 

            <div class="center__summary__other">
                <span class="center__type">{{ center.type }}</span>
            </div>
        </li>
        {% endfor %}
        </ul>

    
    {% else %}
        <!-- 센터 쿼리셋이 존재하지 않을 때 -->
            {% if query %}
        <!-- 검색어가 있어 query가 context로 넘어오면 검색결과가 없음 -->
        <span class="center__message">
        일치하는 검색 결과가 없습니다.
        </span>
            {% else %}
        <!-- query가 없으면 검색어가 아니며 센터가 존재하지 않으므로 검색결과 없음-->
        <span class="center__message">
        검색 결과가 없습니다. 검색어를 입력해주세요.
        </span>
            {% endif %}

    {% endif %}
    
    <!-- Arrow button -->
    <button class="arrow-up">
        <i class="fas fa-chevron-circle-up"></i>
    </button>




    <div id="center_list_ajax"></div> <!--Ajax 결과물을 추가할 곳-->
    <input id="page" type="hidden" value="2"> <!--페이지 정보를 입력할 곳-->
    <input id="userX" type="hidden" value="{{ userX }}"/>
    <input id="userY" type="hidden" value="{{ userY }}"/>
    <input id="query" type="hidden" value="{{ query }}"/>


    <!--<button id="callmorecenter" type="button" class="btn btn-primary btn-block">Loading...</button> 페이지 스크롤 이벤트가 작동하지 않을 경우 클릭함.-->
    </ul>
</div>


<script>
//scroll event

$('#callmorecenter').click(function(){
    var page = $('#page').val();
    callMoreCenterAjax(page);
    $('#page').val(parseInt(page)+1);
});

$('.center__list').scroll(function(){
    var scrollHeight = $('.center__list').scrollTop() + $('.center__list').height();
    var documentHeight = $('.center__item').height() * 10 + $('#center_list_ajax').height()
    
    if (scrollHeight + 500 >= documentHeight){
        callMoreCenterAjax(page);
    }
});

const query = $('#query').val();
const userX = $('#userX').val();
const userY = $('#userY').val();

var isLoading = false;

function callMoreCenterAjax(page) {
    if (isLoading) return;

    var page = $('#page').val();
    isLoading = true;
    $.ajax( {
    type : 'GET',
    url: "{% url 'search:center_list_ajax' %}",
    data: {
    'page': page,
    'query' : query,
    'userX' : userX,
    'userY' : userY,
    
    },
    dataType: 'html',

    success: function(data){
        if (data.length > 10){

        
        const centerItems = $(data)[0].querySelectorAll('.center__item');

            centerItems && centerItems.forEach(item => {
            const distanceData = getText(item, '.center__distance');
            const addressData = getText(item, '.center__address');

            const distance = setDistance(distanceData);
            const address = setAddress(addressData);

            setText(item, '.center__distance', distance);
            setText(item, '.center__address', address);

        
        });

        addMoreCenterAjax(centerItems);

    }
        else 
        return false }
    });
}

//ajax로 가져온 page별 센터 데이터 붙이기
function addMoreCenterAjax(data, textStatus, jqXHR) {
    isLoading = false;

        $('#center_list_ajax').append(data);

        var page = $('#page').val();
        $('#page').val(parseInt(page)+1);
}



// html 태그의 내용 가져오기 
function getText(parent, selector){
    const text = parent.querySelector(selector).innerHTML;
    return text;
}

// html 태그 안에 내용 넣기
function setText(parent, selector, text){
    const tag = parent.querySelector(selector);
    tag.textContent = text;
}

// 주소 요약 하기
function setAddress(address){
    const longAddress = address.split(' ');
    const shortAddress = `${longAddress[0]} ${longAddress[1]||''} ${longAddress[2]|| ''} `;
    return shortAddress;
}

// 거리 단위 설정 
function setDistance(distance){
    if(distance < 1){
        distance = `${distance * 1000}m`;
    }else{
        distance= `${Math.round(distance *10)/10}km`;
    }
    return distance;
}


</script>



{% endblock %}

search/templates/search/center_list_ajax.html
{% if centers %}
<ul id="center__parts">
    {% for center in centers %}
    <li class="center__item" data-distance = "{{ center.distance }}" data-score = "{{ center.review.0.score__avg|floatformat }}">
        <div class="center__summary__main">
            <a href="{% url 'centers:index' center.id %}" class="center__name" target="_blank">{{ center.name }}</a>
            <div class="center__location">
                <span class="center__distance">{{ center.distance }}</span>
                <span class="divider"></span>
                <span class="center__address">{{ center.address }}</span>
            </div>
            
            <div class="center__review">

                {% if center.review %}
                <span class="center__average">★ {{ center.review.0.score__avg|floatformat }}</span>  

                {% else %}
                <span class="center__average">★ 0.0</span> 
                {% endif %}
                
                <span class="divider"></span>
                <span class="center__counts">리뷰  
                    {% if center.review %}
                    <span>{{ center.review.0.score__count }}</span>  
                    {% else %}
                    <span>0</span>
                    {% endif %}</span>
                    
            </div>
        </div> 

        <div class="center__summary__other">
            <span class="center__type">{{ center.type }}</span>
        </div>
    </li>
    {% endfor %}
</ul>

{% else %}

{% if query %}

{% else %}
<!-- query가 없으면 검색어가 아니며 센터가 존재하지 않으므로 검색결과 없음-->
<span class="center__message">
    검색 결과가 없습니다. 검색어를 입력해주세요.
</span>
{% endif %}

{% endif %}

search/templates/search/index.html
{% extends "navbar.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'search/style.css' %}" type="text/css" />
<script type="module" src="{% static 'search/main.js' %}" defer></script>
{% endblock %}

{% block content %}


<!-- search-bar -->
<section id="search-bar" class="header">
    <button type="button" class="btn back__btn">
        <i class="fas fa-chevron-left"></i>
    </button>
    <form action="{% url 'search:center_list' %}" method="GET" enctype="multipart/form-data">


        <input class="search-bar__input" placeholder="상담 유형, 위치, 센터명을 검색해보세요" name="query" autocomplete="off"/>
        <button type="button" class="search-bar__icon cancel__icon inactive">
            <i class="fas fa-times-circle"></i>
        </button>
        <span class="search-bar__icon search__icon">
            <i class="fa fa-search"></i>
        </span>
        </input>

        <input type="hidden" name="userX" />
        <input type="hidden" name="userY" />

    </form>

</section>




<!-- main  -->
<section id="search-main" class="main">
    <h4>추천 검색어</h4>
    <ul class="hashtags">
        {% for hashtag in hashtag_top10 %}
        <li class ="hashtag__item">
            <form action="{% url 'search:center_list' %}" method="GET" enctype="multipart/form-data">
                <button type="submit" class= "hashtag__text"> {{ hashtag }} </button>   
                <input type="hidden" name="query" value= "{{ hashtag|cut:'#' }}" />
                <input type="hidden" name="userX" />
                <input type="hidden" name="userY" />
        
            </form> 
        </li>
        {% endfor %}
        
    </ul>
</section>



{% endblock %}