accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('sign-up/', views.sign_up, name = 'sign_up'),
    path('<int:profile_id>/complete/', views.complete, name = 'complete'), 
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('check_id_duplicate/', views.check_id_duplicate, name = 'id_check'),
]

beParents/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('accounts.urls', namespace='index')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('map/', include('map.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('search/', include('search.urls')),
    path('centers/', include('centers.urls')),
    path('mypage/', include('mypage.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

centers/urls.py
from django.urls import path
from . import views

app_name = 'centers'

urlpatterns = [

    path('<int:center_id>/', views.index, name = 'index'),
    path('<int:center_id>/reviews/new', views.reviews, name = 'reviews'),
    path('<int:center_id>/reviews/save', views.save, name = 'save'),
    path('<int:center_id>/<int:review_id>/edit', views.edit, name = 'edit'),
    path('<int:center_id>/<int:review_id>/update', views.update, name = 'update'),
    path('<int:center_id>/<int:review_id>/delete/', views.delete, name = 'delete'),
    path('<int:center_id>/like/', views.like, name = 'like'),

]

map/urls.py
from django.urls import path

from . import views

app_name = 'map'

urlpatterns = [
    path('', views.index, name = 'index'),
    #path('<int:center_id>/center_summary/', views.center_summary, name = 'center_summary'),
    path('ajax/', views.ajax, name = 'ajax'),
]

mypage/urls.py
from django.urls import path

from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('mylikes/', views.mylikes, name = 'mylikes'),
    path('myreviews/', views.myreviews, name = 'myreviews'),
    path('myinfo/', views.myinfo, name = 'myinfo'),

   
]

mypage/models.py
from django.db import models
from django.contrib.auth.models import User
from centers.models import Center, CenterReview, CenterLike
from accounts.models import Profile

# Create your models here.

mypage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils import timezone
from .models import Center, CenterLike, CenterReview, Profile
from django.contrib.auth.decorators import login_required



# Create your views here.
def index(request):
    profile = None
    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)

    context = {
        'profile' : profile
    }
    return render(request, 'mypage/index.html', context)

@login_required
def mylikes(request):
    likes = CenterLike.objects.filter(user=request.user)
    
    context = {
        'likes' : likes

    }
    return render(request, 'mypage/mylikes.html', context)

@login_required
def myreviews(request):
    reviews = CenterReview.objects.filter(user=request.user).order_by('-created_at')

    context = {
        'reviews':reviews

    }
    return render(request, 'mypage/myreviews.html', context)

@login_required
def myinfo(request):
    return render(request, 'mypage/myinfo.html')

    

mypage/templates/mypage/index.html
{% extends "navbar.html" %}

{% load static %}

{% block style %}
    <link rel = "stylesheet" href = "{% static 'mypage/style.css' %}" type = "text/css" />
    <script type="module" src="{% static 'mypage/main.js' %}" defer></script>
{% endblock %}

{% block content %}

<!-- 로그인한 상태 -->
{% if user.is_authenticated %}
<!-- header -->
<header id="mypage-name" class="header">
    <h2>{{ profile.user_realname }}님</h2>
</header>

<!-- main -->
<section id="mypage-main">
    <ul class="mypage__list" id="mypage__records">
        <li class="mypage__likes">
            <a href="{% url 'mypage:mylikes' %}" class="mypage__item">
                <span class="mypage__title">찜한 센터</span>
                <span class="btn__arrow">
                    <i class="fas fa-chevron-right"></i>
                </span>
            </a>
        </li>
        <li class="mypage__reviews">
            <a href="{% url 'mypage:myreviews' %}" class="mypage__item">
                <span class="mypage__title">나의 후기</span>
                <span class="btn__arrow">
                    <i class="fas fa-chevron-right"></i>
                </span>
            </a>
        </li>
    </ul>

    <ul class="mypage__list" id="mypage__accounts">
        <li class="mypage__likes">
            <a href="{% url 'mypage:myinfo' %}" class="mypage__item">
                <span class="mypage__title">개인정보 수정</span>
                <span class="btn__arrow">
                    <i class="fas fa-chevron-right"></i>
                </span>
            </a>
        </li>
        <li class="mypage__logout">
            <form action="{% url 'accounts:logout' %}" method="POST" id="logout">
                {% csrf_token %}
                <button type="button" class="btn__logout">로그아웃</button>
            </form>
        </li>
    </ul>
</section>

<!-- logout popup -->
<section id="pop-up" class="pop-up__hide">
    <div class="pop-up__window">
        <span class="pop-up__context"></span>
        <div class="btn__container">
            <button type="button" class="pop-up__btn btn-disagree">아니오</button>
            <button type="submit" form="logout" class="pop-up__btn btn-agree">네</button>
        </div>
    </div>
</section>

<!-- 로그인하지 않은 상태 -->
{% else %}

<!-- header -->
<header id="mypage-anonymous" class="header">
    <h2>마이페이지</h2>
    <a href="{% url 'accounts:login' %}?next={{request.path}}" class="btn__login">로그인</a>
</header>

<!-- main -->
<section id="mypage-main">
    <ul class="mypage__list" id="mypage__records">
        <li class="mypage__item anonymous">
            <span class="mypage__title">찜한 센터</span>
            <span class="btn__arrow">
                <i class="fas fa-chevron-right"></i>
            </span>
        </li>
        <li class="mypage__item anonymous">
            <span class="mypage__title">나의 후기</span>
            <span class="btn__arrow">
                <i class="fas fa-chevron-right"></i>
            </span>
        </li>
    </ul>

    <ul class="mypage__list" id="mypage__accounts">
        <li class="mypage__item anonymous">
            <span class="mypage__title">개인정보 수정</span>
            <span class="btn__arrow">
                <i class="fas fa-chevron-right"></i>
            </span>
        </li>
        <li class="mypage__login">
            <a href="{% url 'accounts:login' %}?next={{request.path}}" class="mypage__title">로그인 / 회원가입</a>
        </li>
    </ul>
</section>

<!-- login popup -->
<section id="pop-up" class="pop-up__hide">
    <div class="pop-up__window">
        <span class="pop-up__context"></span>
        <div class="btn__container">
            <button type="button" class="pop-up__btn btn-disagree">아니오</button>
            <a href="{% url 'accounts:login' %}?next={{request.path}}">
                <button type="button" class="pop-up__btn btn-agree">예</button>
            </a>
        </div>
    </div>
</section>
{% endif %}

{% endblock %}

mypage/templates/mypage/mylikes.html
{% extends "navbar.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'mypage/style.css' %}" type="text/css" />
<script type="module" src="{% static 'mypage/mypages.js' %}" defer></script>
{% endblock %}

{% block content %}

<!-- header -->
<header id="my-likes" class="header">
    <button class="btn back__btn">
        <i class="fas fa-chevron-left"></i>
    </button>
    <h3>찜한 센터</h3>
</header>

<!-- main -->
<section id="my-likes-main" class="main">

    {% if likes %}
    <ul class="my-likes__list">
        {% for like in likes %}
        <li class="my-likes__item">
            <div class="my-likes__title">
                <a href="{% url 'centers:index' like.center.id %}" class="my-likes__name">
                    {{like.center.center_name}}
                </a>
                <form action="{% url 'centers:like' like.center.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="my-likes__bookmark">
                        <i class="fas fa-bookmark"></i>
                    </button>
                </form>
            </div>

            <div class="my-likes__location">
                <span class="my-likes__address">{{ like.center.center_address }}</span>
            </div>
        </li>
        {% endfor %}
    </ul>

    <!-- Arrow button -->
    <button class="arrow-up">
        <i class="fas fa-chevron-circle-up"></i>
    </button>

    {% else %}
    <span class="center__message">
        찜한 센터가 없습니다.
    </span>
    {% endif %}
</section>

{% endblock %}

mypage/templates/mypage/myreviews.html
{% extends "navbar.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'mypage/style.css' %}" type="text/css" />
<script type="module" src="{% static 'mypage/mypages.js' %}" defer></script>
{% endblock %}

{% block content %}
<!-- header -->
<header id="my-reviews" class="header">
    <button class="btn back__btn">
        <i class="fas fa-chevron-left"></i>
    </button>
    <h3>나의 리뷰</h3>
</header>

<!-- main -->
<section id="my-reviews-main" class="main">

    {% if reviews %}
    <ul class="my-reviews__list">
        {% for review in reviews %}
        <li class="my-reviews__item">
            <div class="my-reviews__header">
                <div class="my-reviews__title">
                    <a href="{% url 'centers:index' review.center.id %}" class="my-reviews__name">
                        {{review.center.center_name}}
                    </a>
                    <div class="my-reviews__icon">
                        <a href="{% url 'centers:edit' review.center.id review.id %}?next={{request.path}}">
                            <i class="far fa-edit"></i>
                        </a>
                        <a class="my-reviews__delete">
                            <i class="far fa-trash-alt"></i>
                            <div id="centerId" style="display: none;">{{ review.center.id }}</div>
                            <div id="reviewId" style="display: none;">{{ review.id }}</div>
                        </a>
                    </div>
                </div>

        

                <div class="my-reviews__info">
                    <span class="my-reviews__score">★ {{review.score}}</span>
                    <span class="divider"></span>
                    <span class="my-reviews__created_at">{{ review.created_at }}</span>
                </div>
            </div>
            <p class="my-reviews__contents">{{review.content|truncatechars:20}}</p>
        </li>
        {% endfor %}
    </ul>

    <!-- Arrow button -->
    <button class="arrow-up">
        <i class="fas fa-chevron-circle-up"></i>
    </button>

    {% else %}
    <span class="center__message">
        등록한 리뷰가 없습니다.
        </br> 평가를 남겨주세요.
    </span>
    {% endif %}
</section>

<!-- popup -->
<section id="pop-up" class="pop-up__hide">
    <div class="pop-up__window">
        <span class="pop-up__context"></span>
        <div class="btn__container">
            <button type="button" class="pop-up__btn btn-disagree">아니오</button>
            <button type="button" class="pop-up__btn btn-agree">네</button>
        </div>
    </div>
</section>

{% endblock %}