beParents/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('accounts.urls', namespace='index')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('map/', include('map.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('search/', include('search.urls')),
    path('centers/', include('centers.urls')),
    path('mypage/', include('mypage.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name = 'index'),
]

map/urls.py
from django.urls import path

from . import views

app_name = 'map'

urlpatterns = [
    path('', views.index, name = 'index'),
    #path('<int:center_id>/center_summary/', views.center_summary, name = 'center_summary'),
    path('ajax/', views.ajax, name = 'ajax'),
]

mypage/urls.py
from django.urls import path

from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('mylikes/', views.mylikes, name = 'mylikes'),
    path('myreviews/', views.myreviews, name = 'myreviews'),
    path('myinfo/', views.myinfo, name = 'myinfo'),

   
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [

    path('', views.index, name = 'index'),
    path('center_list/', views.center_list, name = 'center_list'),
    path('center_list_ajax/', views.center_list_ajax, name = 'center_list_ajax'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
    
    <title>be Parents</title>
    <link rel = "stylesheet" href = "{% static 'style/base.css' %}" type = "text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700&display=swap"
    rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css"
    integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" defer></script>
    {% block style %}
    {% endblock %}
    
    </head>

    <body>

        <div class="container">

            {% block content %}
            {% endblock %}
        
        </div>

    </body>
    
</html>

templates/navbar.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
    
    <title>be Parents</title>
    
    <link rel = "stylesheet" href = "{% static 'style/navbar.css' %}" type = "text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700&display=swap"
    rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css"
    integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" defer></script>
    <script src="/static/scripts/navbar.js" defer></script>
    {% block style %}
    {% endblock %}

    </head>

    <body>

        <div class="container">

            {% block content %}
            {% endblock %}
    
            <!-- nav bar -->
            <nav class="navbar">
                <ul class="navbar__menu">
                    <li class="navbar__menu__item current" id="navbar__home">
                        <a href="{% url 'home:index' %}">
                            <i class="fas fa-home"></i>
                            홈
                        </a>
                    </li>
                    <li class="navbar__menu__item" id="navbar__search">
                        <a href="{% url 'search:index' %}">
                            <i class="fas fa-search"></i>
                            검색
                        </a>
                    </li>
                    <li class="navbar__menu__item" id="navbar__map">
                        <a href="{% url 'map:index' %}">
                            <i class="fas fa-map-marked-alt"></i>
                            지도
                        </a>
                    </li>
                    <li class="navbar__menu__item" id="navbar__mypage">
                        <a href="{% url 'mypage:index' %}">
                            <i class="fas fa-user"></i>
                            마이페이지
                        </a>
                    </li>
                </ul>
            </nav>
        </div>


        {% if messages %}
        {% for message in messages %}
        {% if message.tags %}
        <script>
            alert("{{ message.message }}")
        </script>
        {% endif %}
        {% endfor %}
        {% endif %}
    </body>
    
</html>