beParents/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('accounts.urls', namespace='index')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('map/', include('map.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('search/', include('search.urls')),
    path('centers/', include('centers.urls')),
    path('mypage/', include('mypage.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

centers/urls.py
from django.urls import path
from . import views

app_name = 'centers'

urlpatterns = [

    path('<int:center_id>/', views.index, name = 'index'),
    path('<int:center_id>/reviews/new', views.reviews, name = 'reviews'),
    path('<int:center_id>/reviews/save', views.save, name = 'save'),
    path('<int:center_id>/<int:review_id>/edit', views.edit, name = 'edit'),
    path('<int:center_id>/<int:review_id>/update', views.update, name = 'update'),
    path('<int:center_id>/<int:review_id>/delete/', views.delete, name = 'delete'),
    path('<int:center_id>/like/', views.like, name = 'like'),

]

map/urls.py
from django.urls import path

from . import views

app_name = 'map'

urlpatterns = [
    path('', views.index, name = 'index'),
    #path('<int:center_id>/center_summary/', views.center_summary, name = 'center_summary'),
    path('ajax/', views.ajax, name = 'ajax'),
]

centers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import os
from django.conf import settings

class Center(models.Model):
    n_id = models.IntegerField(null=True)
    center_name = models.CharField(max_length=100, null=True)
    center_type = models.CharField(max_length=100, null=True)
    center_phone = models.CharField(max_length=100, null=True)
    center_address = models.CharField(max_length=100, null = True)
    homepage = models.CharField(max_length=200, null=True)
    runhours = models.CharField(max_length=200, null=True)
    hashtags = models.JSONField(default=list, null=True)

    content_urls = models.JSONField(default=list, null=True)
    contents = models.JSONField(default=list, null=True)
    x = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    y = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    like_users = models.ManyToManyField(User, through = 'CenterLike', related_name='like_centers', null = True)
    review_users = models.ManyToManyField(User,through='CenterReview', related_name='review_centers', null = True)


    def __str__(self):
            return f'{self.id}: {self.center_name} : {self.center_type} : {self.center_phone} : {self.center_address} :{self.homepage} : {self.runhours} : {self.hashtags} : {self.content_urls} : {self.contents} : {self.x} : {self.y}'


class CenterReview(models.Model):
    center = models.ForeignKey(Center, on_delete=models.CASCADE, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    content = models.TextField(null = True)
    score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], null = True)
    created_at = models.DateTimeField(auto_now_add=True, null = True)
    image = models.ImageField(blank=True, null=True, upload_to='centers')
    
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.name))
        super(CenterReview, self).delete(*args, **kargs)

    def __str__(self):

        if self.user:
            return f' {self.user.get_username()} : {self.center.center_name} : {self.score} : {self.content}'
            
        return f'{self.score} : {self.content}'



class CenterLike(models.Model):
    center = models.ForeignKey(Center, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, null = True)

    def __str__(self):

        if self.user:
            return f'{self.user.get_username()} : {self.center.center_name} : {self.created_at}'
            
        return None








    

centers/views.py
import os
from django.shortcuts import render, redirect
from .models import Center, CenterReview, CenterLike
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from django.http import HttpResponseRedirect

# Create your views here.
#센터 상세페이지
def index(request, center_id):
    center = Center.objects.get(id=center_id)
    reviews = CenterReview.objects.filter(center = center).order_by('-created_at')
    avg_score = CenterReview.objects.values('center').annotate(Avg('score')).filter(center=center)
    NAVER_KEY = os.environ['NAVER_KEY']

    context = {
        'reviews': reviews,
        'center' : center,
        'avg_score' : avg_score,
        'naver_key' : NAVER_KEY 
    }

    return render(request, 'centers/index.html', context)


#리뷰 작성하기
@login_required
def reviews(request, center_id):
    center = Center.objects.get(id=center_id)
    context = {'center': center }

    return render(request, 'centers/reviews.html', context)


#리뷰 저장
@login_required
def save(request, center_id):
    center = Center.objects.get(id=center_id)

    user = request.user
    content = request.POST['content']
    score = request.POST['score']

    image = None
    if 'image' in request.FILES:
        image = request.FILES['image']

    review = CenterReview(user=user, center=center, content=content, score = score, image=image, created_at=timezone.now())
    review.save()

    return redirect('centers:index', center_id = center.id)


#리뷰 수정하기
@login_required
def edit(request, center_id, review_id):
    try:
        center = Center.objects.get(id=center_id)
        review = CenterReview.objects.get(id=review_id, user=request.user)
        next = request.GET.get('next', '')
    except CenterReview.DoesNotExist:
        return redirect('centers:index', center_id = center.id)

    context = {
        'review': review,
        'center' : center,
        'next' : next,
        }
    return render(request, 'centers/edit.html', context)


#리뷰 수정한거 업데이트
@login_required
def update(request, center_id, review_id):
    try:
        review = CenterReview.objects.get(id=review_id, center=center_id, user=request.user)
    except CenterReview.DoesNotExist:
        return redirect('centers:index', center_id = review.center.id)

    review.content = request.POST['content']
    review.score = request.POST['score']
    delete_image = request.POST.get('image__delete', '')
    next=request.POST['next']

    if delete_image == 'delete':
        review.image.delete()

    if 'image' in request.FILES:
        review.image = request.FILES['image']

    review.save()

    return redirect(next)

#리뷰 삭제

def delete(request, center_id, review_id):
    try:
        center = Center.objects.get(id=center_id)
        review = CenterReview.objects.get(id=review_id, user=request.user)
    except CenterReview.DoesNotExist:
        return redirect('centers:index', center_id = center.id)

    review.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


#센터 찜

def like(request, center_id):

    if request.method == 'POST':
        
        try:
            center = Center.objects.get(id=center_id)
            center_like = CenterLike.objects.all()

            if request.user in center.like_users.all():
                center.like_users.remove(request.user)

            else:
                center.like_users.add(request.user)
                user = request.user
                user.save()

            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


        except Center.DoesNotExist:
            pass
        
    return redirect('centers:index', center_id = center.id)

centers/templates/centers/edit.html
{% extends "navbar.html" %}

{% load static %}

{% block style %}
    <link rel = "stylesheet" href = "{% static 'centers/style.css' %}" type = "text/css" />
    <script type="module" src="{% static 'centers/reviews.js' %}" defer></script>
{% endblock %}

{% block content %}

<header id="review" class="header">
    <div class="header__left">
        <button class="back__btn">
            <i class="fas fa-chevron-left"></i>
        </button>
        <h3 class="review__name">{{ center.center_name }}</h3>
    </div>
    <button type="button" class="submit__btn" form="review__form">
            수정
    </button>
</header>

<form action="{% url 'centers:update' center.id review.id %}" id="review__form" class="main" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="review__score">
        <div id="score" style="display: none;">{{ review.score }}</div>
        <!-- 해당 별점을 클릭하면 해당 별과 그 왼쪽의 모든 별의 체크박스에 checked 적용 -->
        <input type="checkbox" name="score" id="score1" value="1" class="rate__radio" title="1점" />
        <label for="score1"></label>

        <input type="checkbox" name="score" id="score2" value="2" class="rate__radio" title="2점" />
        <label for="score2"></label>

        <input type="checkbox" name="score" id="score3" value="3" class="rate__radio" title="3점" />
        <label for="score3"></label>

        <input type="checkbox" name="score" id="score4" value="4" class="rate__radio" title="4점" />
        <label for="score4"></label>

        <input type="checkbox" name="score" id="score5" value="5" class="rate__radio" title="5점" />
        <label for="score5"></label>

        <p class="error__message"></p>
    </div>
    <textarea name= "content" placeholder="이 센터의 후기를 들려주세요 (최대 500자)" maxlength="500">{{ review.content }}</textarea>
    
    <input type="file" class="review__image" id="image" name="image" accept="image/*"/>
    <label class="review__image__icon" for= "image">
        <i class="fas fa-camera"></i>
        사진 첨부하기 <span>(첨부 파일 변경시 기존 파일은 삭제됩니다)</span>
    </label>
    
    <div id="image__preview">
        {% if review.image %}
        <img src="{{ review.image.url }}" class="image__uploaded" />
        <input type="checkbox" name = "image__delete" class="image__delete" value="delete">
        {% endif %}
    </div>
    
    <input type="hidden" name="next" value="{{ next }}">
</form>


<!-- popup -->
<section id="pop-up" class="pop-up__hide">
    <div class="pop-up__window">
        <span class="pop-up__context"></span>
        <div class="btn__container">
            <button type="button" class="pop-up__btn btn-disagree">아니오</button>
            <button class="pop-up__btn btn-agree">네</button>
        </div>
    </div>
</section>
{% endblock %}

centers/templates/centers/index.html
{% extends "navbar.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'centers/style.css' %}" type="text/css" />
<script type="module" src="{% static 'centers/main.js' %}" defer></script>
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId={{ naver_key }}"></script>

{% endblock %}

{% block content %}
<!-- 센터 좌표 js로 내보내기 -->
<div id="centerX" style="display: none;">{{ center.x }}</div>
<div id="centerY" style="display: none;">{{ center.y }}</div>

<!-- header -->
<header id="center" class="header">
    <div class="header__left">
        <h3 class="center__name">{{ center.center_name }}</h3>
    </div>

    {% if user.is_authenticated %}
    <form action="{% url 'centers:like' center.id %}" method="POST">
        {% csrf_token %}

        {% if user in center.like_users.all %}
        <button type="submit" class="center__bookmark">
            <i class="fas fa-bookmark"></i>
        </button>
        {% else %}
        <button type="submit" class="center__bookmark">
            <i class="far fa-bookmark"></i>
        </button>
        {% endif %}
        
    </form>
    {% else %}
    <button type="button" class="center__bookmark anonymous">
        <i class="far fa-bookmark"></i>
    </button>
    {% endif %}
</header>

<!-- main: center-detail -->
<section id="center__detail" class="main">
    <div id="center__map"></div>

    <div class="center__info">
        <h4>기본 정보</h4>

        <ul class="center__info__list">
            <li class="info__item">
                <span class="info__icon"><i class="fas fa-map-marker-alt"></i></span>
                <span class="info__description">{{ center.center_address }}</span>
            </li>

            <li class="info__item" id="runhours">
                <span class="info__icon"><i class="fas fa-clock"></i></span>
                <span class="info__description"> {{ center.runhours }} </span>
                <a href="javascript:void(0)" class="btn__fold">
                    <i class="fas fa-chevron-down"></i>
                </a>
            </li>

            <li class="info__item">
                <span class="info__icon"><i class="fas fa-globe"></i></span>
                <a href="{{ center.homepage }}" class="info__description homepage" target="_blank">
                    {{ center.homepage }}
                </a>
            </li>
            <li class="info__item">
                <span class="info__icon"><i class="fas fa-phone-alt"></i></span>
                <span class="info__description">{{ center.phone }}</span>
            </li>


            {% if center.hashtags %}
            <li class="info__item hashtags">
                <span class="info__icon"><i class="fas fa-tag"></i></span>
                <ul class="info__description">
                    {% for hashtag in center.hashtags %}
                    <li class="center__hashtag">
                        <a>{{ hashtag }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            {% endif %}
        </ul>
    </div>

    <div class="center__review">
        <div class="center__review__header">
            <div class="center__review__description">

                <h4 class="review__counts">리뷰
                    {% if reviews %}
                    <span>{{ reviews.count }}</span>
                    {% else %}
                    <span>0</span>
                    {% endif %}
                </h4>

                {% if user.is_authenticated %}
                <a href="{% url 'centers:reviews' center.id %}" class="review__add__btn">
                    <i class="far fa-edit"></i>
                </a>
                {% else %}
                <button type="button" class="review__add__btn anonymous">
                    <i class="far fa-edit"></i>
                </button>
                {% endif %}

            </div>

            {% if avg_score %}
            <h3 class="center__review__average">★ {{ avg_score.0.score__avg|floatformat }}</h3>
            
            {% else %}
            <h3 class="center__review__average">★ 0.0</h3>
            {% endif %}

        </div>

        {% if reviews %}
        <ul class="center__review__list">

            {% for review in reviews %}
            <li class="center__review__item">
                <div class="item__header">
                    <div class="item__header__left">
                        <span class="center__review__score">★ {{ review.score }}</span>
                        <div class="center__review__profile">
                            <span class="profile__user">{{ review.user }}</span>
                            <span class="divider"></span>
                            <span class="profile__created_at">{{ review.created_at }}</span>
                        </div>
                    </div>

                    {% if user == review.user %}
                    <div class="center__review__edit">
                        <span class="edit__icon">
                            <i class="fas fa-ellipsis-v"></i>
                        </span>
                        <div class="edit__option inactive">
                            <a href="{% url 'centers:edit' center.id review.id %}?next={{request.path}}" class="option__item">수정하기</a>
                            <a class="option__item option__delete">삭제하기
                                <div id="centerId" style="display: none;">{{ center.id }}</div>
                                <div id="reviewId" style="display: none;">{{ review.id }}</div>
                            </a>
                            
                        </div>
                    </div>
                    {% endif %}

                </div>
                <div class="center__review__contents">
                    <div>
                        <span class="center__review__text">
                            {{ review.content}}
                        </span>
                        <a href="javascript:void(0)" class="btn__fold">
                            <i class="fas fa-chevron-down"></i>
                        </a>
                    </div>
                    {% if review.image %}
                    <a href="{{ review.image.url }}" class="center__review__photo" target="_blank">
                        <img src="{{ review.image.url }}" alt="photo" />
                    </a>
                    {% endif %}

                </div>
            </li>
            {% endfor %}

        </ul>

        {% else %}
        <span class="center__message"> 작성된 리뷰가 없습니다.
            </br>평가를 남겨주세요. </span>
        {% endif %}

    </div>
    <!-- Arrow button -->
    <button class="arrow-up">
        <i class="fas fa-chevron-circle-up"></i>
    </button>
</section>

<!-- popup -->
<section id="pop-up" class="pop-up__hide">
    <div class="pop-up__window">
        <span class="pop-up__context"></span>
        <div class="btn__container">
            <button type="button" class="pop-up__btn btn-disagree">아니오</button>
            <button type="button" class="pop-up__btn btn-agree">네</button>
        </div>
    </div>
</section>


{% endblock %}

centers/templates/centers/reviews.html
{% extends "navbar.html" %}

{% load static %}

{% block style %}
    <link rel = "stylesheet" href = "{% static 'centers/style.css' %}" type = "text/css" />
    <script type="module" src="{% static 'centers/reviews.js' %}" defer></script>
{% endblock %}

{% block content %}
<header id="review" class="header">
    <div class="header__left">
        <button class="back__btn">
            <i class="fas fa-chevron-left"></i>
        </button>
        <h3 class="review__name">{{ center.center_name }}</h3>
    </div>
    <button type="button" class="submit__btn" form="review__form">
            등록
    </button>
</header>

<form action="{% url 'centers:save' center.id %}" id="review__form" class="main" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="review__score">
        <!-- 해당 별점을 클릭하면 해당 별과 그 왼쪽의 모든 별의 체크박스에 checked 적용 -->
        <input type="checkbox" name="score" id="score1" value="1" class="rate__radio" title="1점" />
        <label for="score1"></label>

        <input type="checkbox" name="score" id="score2" value="2" class="rate__radio" title="2점" />
        <label for="score2"></label>

        <input type="checkbox" name="score" id="score3" value="3" class="rate__radio" title="3점" />
        <label for="score3"></label>

        <input type="checkbox" name="score" id="score4" value="4" class="rate__radio" title="4점" />
        <label for="score4"></label>

        <input type="checkbox" name="score" id="score5" value="5" class="rate__radio" title="5점" />
        <label for="score5"></label>

        <p class="error__message"></p>
    </div>
    <textarea name= "content" placeholder="이 센터의 후기를 들려주세요 (최대 500자)"
    maxlength="500"></textarea>
    
    
    <input type="file" class="review__image" id="image" name="image" accept="image/*"/>
    <label class="review__image__icon" for= "image">
        <i class="fas fa-camera"></i>
        사진 첨부하기 
        <span>(최대 1장)</span>
    </label>
    <div id="image__preview">
        <div id="centerId" style="display: none;">{{ center.id }}</div>
        <div id="reviewId" style="display: none;">{{ review.id }}</div>
    </div>

</form>

<!-- popup -->
<section id="pop-up" class="pop-up__hide">
    <div class="pop-up__window">
        <span class="pop-up__context"></span>
        <div class="btn__container">
            <button type="button" class="pop-up__btn btn-disagree">아니오</button>
            <button class="pop-up__btn btn-agree">네</button>
        </div>
    </div>
</section>
{% endblock %}